### PR TITLE
Update ally.css

### PR DESCRIPTION
**Pull request by Guizzu**
Fix options (start) button glyph.

### CODE REVIEW

**Comment by semakusut** [comment]
I deliberately made the icon like that, to remind me to open the QAM menu

**Comment by Guizzu** [comment]
Got it, although it doesn't match the button that opens the context menu on big picture.
I can just maintain my own fork of the theme if that's the case.

Thank you!

**Comment by semakusut** [comment]
thx, yaps you can use your fork for personal use

**Comment by Guizzu** [comment]
Closed.
Intended feature, not a bug.

**Pull request closed without merging**
